### ISSUE TITLE
Consider changing action parameters to be `snake_case`

### ISSUE THREAD

**Issue by mfurtak** [hjanuschka/fastlane-plugin-sharethemeal#3]
Hi @hjanuschka 👋 

This looks like a really cool plugin - nice work!

I just wanted to leave the suggestion to make the action parameters be named with `snake_case` rather than `camelCase` to better fit with the default _fastlane_ and Ruby style. Something like:

``` ruby
sharethemeal(
  amount: "0.4",
  user_hash: "xxxxx",
  language: "de",
  beneficiary_uri: "xxxxx",
  beneficiary_source: "contentful",
  thank_you_uri: "xxxxxx"
)
```

Cheers! 🚀

**Comment by hjanuschka** [comment]
Thank You - done with 99f4308f49ce1acefc77f92d4685eb45fdac7653
